#!/usr/bin/env ansible-playbook
---
# file: setup-rhel.yaml
- hosts: localhost
  become: True

  tasks:
  - name: Define .bashrc location
    dnf:
      state: present
      name: "{{ item }}"
    loop:
    - bind-utils
    - iproute
    - net-tools
    tags:
    - never
